name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  create_release:
    name: Deploy Canary
    runs-on: ubuntu-latest
    steps:
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # SENTRY_URL: https://sentry.io/
          version: 'v1.0.1'
        with:
          environment: canary
          ignore_empty: true

  deploy_production_canary:
    name: Deploy Canary
    runs-on: ubuntu-latest
    environment:
      name: "canary"
    steps:
      - name: hello world
        run: echo "Hello, world!"
